import { supabaseServer } from "@/lib/supabase/server";
import { PageHeader } from "@/components/PageHeader";
import { guardView } from "@/lib/guard";
import Link from "next/link";
import { ChevronRight } from "lucide-react";

export const dynamic = "force-dynamic";

const nat = new Intl.Collator(undefined, { numeric: true, sensitivity: "base" });

type Row = {
  id: string;
  name: string;
  compound_name: string;
  rent_row_count: number;
  active_lessee: string | null;
};

export default async function BackfillIndex() {
  await guardView("view_rent");
  const sb = await supabaseServer();

  const [{ data: propsData }, { data: rentCounts }, { data: activeLeases }] = await Promise.all([
    sb.from("properties")
      .select("id, name, compounds(name)")
      .eq("archived", false),
    sb.from("rent_collections").select("property_id"),
    sb.from("leases").select("property_id, lessee_name").eq("active", true),
  ]);

  const countByProp = new Map<string, number>();
  for (const r of rentCounts ?? []) {
    const k = (r as { property_id: string }).property_id;
    countByProp.set(k, (countByProp.get(k) ?? 0) + 1);
  }
  const lesseeByProp = new Map<string, string>();
  for (const l of activeLeases ?? []) {
    lesseeByProp.set((l as { property_id: string }).property_id, (l as { lessee_name: string }).lessee_name);
  }

  const rows: Row[] = (propsData ?? []).map((p: any) => {
    const c = Array.isArray(p.compounds) ? p.compounds[0] : p.compounds;
    return {
      id: p.id,
      name: p.name,
      compound_name: c?.name ?? "—",
      rent_row_count: countByProp.get(p.id) ?? 0,
      active_lessee: lesseeByProp.get(p.id) ?? null,
    };
  });

  rows.sort((a, b) => {
    const c = nat.compare(a.compound_name, b.compound_name);
    return c !== 0 ? c : nat.compare(a.name, b.name);
  });

  // Group by compound
  const groups = new Map<string, Row[]>();
  for (const r of rows) {
    if (!groups.has(r.compound_name)) groups.set(r.compound_name, []);
    groups.get(r.compound_name)!.push(r);
  }

  return (
    <div>
      <PageHeader
        title="Bulk backfill rent"
        actions={<Link href="/rent" className="btn-secondary text-xs">Back to rent</Link>}
      />

      <div className="card mb-4 text-sm">
        <p>
          Pick a property to edit its rent history — an excel-like grid with every month&apos;s rent
          and collected amount. Ideal for backfilling years of historical data quickly.
        </p>
        <p className="text-xs text-muted-fg mt-2">
          Rows are pre-generated by the <em>Backfill rents</em> button on each lease (from lease start
          through current month + 6 months). Use this page to correct amounts row-by-row.
        </p>
      </div>

      <div className="space-y-4">
        {Array.from(groups.entries()).map(([compound, props]) => (
          <div key={compound} className="card p-0">
            <div className="px-3 py-2 bg-muted/40 border-b border-border font-semibold text-sm">
              {compound} <span className="text-muted-fg font-normal">· {props.length} propert{props.length === 1 ? "y" : "ies"}</span>
            </div>
            <div className="divide-y divide-border">
              {props.map((p) => (
                <Link
                  key={p.id}
                  href={`/rent/backfill/${p.id}`}
                  className="flex items-center gap-3 px-3 py-2 hover:bg-muted/50 text-sm"
                >
                  <span className="flex-1 min-w-0">
                    <span className="font-medium">{p.name}</span>
                    {p.active_lessee && <span className="text-xs text-muted-fg block truncate">Lessee: {p.active_lessee}</span>}
                  </span>
                  <span className="text-xs text-muted-fg tabular-nums whitespace-nowrap">
                    {p.rent_row_count} row{p.rent_row_count === 1 ? "" : "s"}
                  </span>
                  <ChevronRight size={14} className="text-muted-fg shrink-0" />
                </Link>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
