// Wipes leases, rent_collections, and auto-generated service-charge costs.
// Keeps: compounds, properties, user_profiles, manually-added costs.
import { config } from "dotenv";
import { Client } from "pg";

config({ path: ".env" });

const client = new Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });

(async () => {
  await client.connect();

  // Use a single transaction so we either wipe everything or nothing.
  await client.query("begin");
  try {
    const r1 = await client.query("delete from public.rent_collections");
    const r2 = await client.query("delete from public.leases");
    // Auto-posted service charge costs (generated by post_monthly_service_charges)
    // Their allocations cascade via FK on costs.id.
    const r3 = await client.query("delete from public.costs where is_auto_service_charge = true");

    await client.query("commit");

    // Sanity counts
    const [props, comps, leases, rents, costs] = await Promise.all([
      client.query("select count(*)::int as n from public.properties"),
      client.query("select count(*)::int as n from public.compounds"),
      client.query("select count(*)::int as n from public.leases"),
      client.query("select count(*)::int as n from public.rent_collections"),
      client.query("select count(*)::int as n from public.costs"),
    ]);

    console.log(`deleted: ${r1.rowCount} rent_collections, ${r2.rowCount} leases, ${r3.rowCount} auto-service-charge costs`);
    console.log("---");
    console.log(`remaining → compounds: ${comps.rows[0].n}, properties: ${props.rows[0].n}, leases: ${leases.rows[0].n}, rent_collections: ${rents.rows[0].n}, costs: ${costs.rows[0].n}`);
  } catch (e) {
    await client.query("rollback");
    throw e;
  }
  await client.end();
})().catch((e) => { console.error("clear failed:", e.message); process.exit(1); });
